### ISSUE TITLE
add this repo to Kebechet

### ISSUE THREAD

**Issue by goern** [AICoE/frauddetection-producer-consumer#2]
Please have Kebechet maintainer this repo using all its managers...

**Comment by harshad16** [comment]
@goern Is release Support required for this repo?

**Comment by goern** [comment]
No I dont think so, this is just a component used in an Open Data Hub Tutorial

**Comment by harshad16** [comment]
okay, the project is been added to kebechet, to add zuul support open a new issue.
this issue can be closed.
